ESX               = nil

TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

ESX.RegisterUsableItem('kiekko', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
				TriggerClientEvent('esx_snus:startuse', source)
end)

ESX.RegisterUsableItem('kiekko1', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	    local snus = xPlayer.getInventoryItem('kiekko1')
	    xPlayer.removeInventoryItem('kiekko1', 1)
				TriggerClientEvent('esx_snus:startuse', source)
end)

ESX.RegisterUsableItem('kiekko2', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
		    local snus = xPlayer.getInventoryItem('kiekko2')
		        xPlayer.addInventoryItem('kiekko1', 1)
	xPlayer.removeInventoryItem('kiekko2', 1)
				TriggerClientEvent('esx_snus:startuse', source)
end)

ESX.RegisterUsableItem('kiekko3', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
    local snus = xPlayer.getInventoryItem('kiekko3')
    xPlayer.addInventoryItem('kiekko2', 1)
	xPlayer.removeInventoryItem('kiekko3', 1)
				TriggerClientEvent('esx_snus:startuse', source)
end)

ESX.RegisterUsableItem('kiekko4', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
		    local snus = xPlayer.getInventoryItem('kiekko4')
		        xPlayer.addInventoryItem('kiekko3', 1)
		    	xPlayer.removeInventoryItem('kiekko4', 1)
				TriggerClientEvent('esx_snus:startuse', source)
end)

ESX.RegisterUsableItem('kiekko5', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
		    local snus = xPlayer.getInventoryItem('kiekko5')
		        xPlayer.addInventoryItem('kiekko4', 1)
		        xPlayer.removeInventoryItem('kiekko5', 1)
				TriggerClientEvent('esx_snus:startuse', source)
end)
